# Generated by Django 5.1.3 on 2024-11-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacient',
            old_name='adresa',
            new_name='diagnostic',
        ),
        migrations.RemoveField(
            model_name='pacient',
            name='data_nasterii',
        ),
        migrations.AddField(
            model_name='pacient',
            name='varsta',
            field=models.IntegerField(default=0),
        ),
    ]
